# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8d7ea58290f0dd2d256d8845171c5baa199cc0668a3d43a0d3d7d6935494ff9ae80ef9e572709d2871d8ac5c2eebbf8e6402641920be81e33506cb2d55a6da

test:
  secret_key_base: 008d0ab61658ebe13780cb652992475e5d28fa104c7b14cc576dd775f4a4440ae08f07606d4b2187444f174c342f2d622e7ab36beed682cd418c1ed67b8f70c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
